name: Renovate
on: workflow_dispatch
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          configurationFile: ./renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}